[project]
name = "sangin"
version = "0.1.0"
description = "TBD"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
  "datasets>=4.0.0",
  "hazm>=0.10.0",
  "pandas>=2.3.1",
  "ruff>=0.12.4",
  "scikit-learn>=1.7.1",
  "transformers>=4.53.3",
  "ty>=0.0.1a15",
]
